### ISSUE TITLE
rhel 8, python 3.7 reports missing lzma

### ISSUE THREAD

**Issue by edavidaja** [rstudio/python-builds#57]
```
[root@rhel /]# /opt/python/"${PYTHON_VERSION}"/bin/python
Python 3.7.14 (default, Nov  3 2022, 02:18:54)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-10)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
/opt/python/3.7.14/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
```

**Comment by heath-r** [comment]
The Dockerfile.centos-8:
https://github.com/rstudio/python-builds/blob/810b26bcd657efed1a392086c22b7907e1b5b4b1/builder/Dockerfile.centos-8

Does not include the `xz-devel` dependency in the `dnf -y install`:
https://github.com/rstudio/python-builds/blob/810b26bcd657efed1a392086c22b7907e1b5b4b1/builder/Dockerfile.rhel-9#L9-L41

Our source instructions here:
https://docs.posit.co/resources/install-python-source/

Use `yum-builddep python3` instead and picks up the dependency:
`[root@rhel /]# dnf config-manager --set-enabled powertools
[root@rhel /]# yum-builddep python3
enabling appstream-source repository
enabling baseos-source repository
enabling powertools-source repository
enabling epel-source repository
Rocky Linux 8 - PowerTools                                                                                                               734 kB/s | 2.8 MB     00:03
Rocky Linux 8 - PowerTools - Source                                                                                                       53 kB/s | 191 kB     00:03
Package tar-2:1.30-6.el8_7.1.x86_64 is already installed.
Package python3-pip-wheel-9.0.3-22.el8.rocky.0.noarch is already installed.
Package python3-setuptools-wheel-39.2.0-6.el8_7.1.noarch is already installed.
Dependencies resolved.
=========================================================================================================================================================================
 Package                                       Architecture              Version                                                     Repository                     Size
=========================================================================================================================================================================
Installing:
 autoconf                                      noarch                    2.69-29.el8                                                 appstream                     709 k
 bluez-libs-devel                              x86_64                    5.63-1.el8                                                  powertools                    114 k
 bzip2                                         x86_64                    1.0.6-26.el8                                                baseos                         59 k
 bzip2-devel                                   x86_64                    1.0.6-26.el8                                                baseos                        223 k
 desktop-file-utils                            x86_64                    0.23-8.el8                                                  appstream                      79 k
 expat-devel                                   x86_64                    2.2.5-10.el8_7.1                                            baseos                         56 k
 findutils                                     x86_64                    1:4.6.0-20.el8                                              baseos                        526 k
 gcc-c++                                       x86_64                    8.5.0-16.el8_7                                              appstream                      12 M
 gdb                                           x86_64                    8.2-19.el8                                                  appstream                     298 k
 gdbm-devel                                    x86_64                    1:1.18-2.el8                                                baseos                         65 k
 git-core                                      x86_64                    2.31.1-3.el8_7                                              appstream                     4.8 M
 glibc-devel                                   x86_64                    2.28-211.el8                                                baseos                         80 k
 gmp-devel                                     x86_64                    1:6.1.2-10.el8                                              baseos                        186 k
 libX11-devel                                  x86_64                    1.6.8-5.el8                                                 appstream                     975 k
 libappstream-glib                             x86_64                    0.7.14-3.el8                                                baseos                        336 k
 libffi-devel                                  x86_64                    3.1-23.el8                                                  baseos                         28 k
 libnsl2-devel                                 x86_64                    1.2.0-2.20180605git4a062cf.el8                              powertools                     34 k
 libtirpc-devel                                x86_64                    1.1.4-8.el8                                                 baseos                        127 k
 mesa-libGL-devel                              x86_64                    22.1.5-2.el8                                                appstream                      51 k
 ncurses-devel                                 x86_64                    6.1-9.20180224.el8                                          baseos                        527 k
 net-tools                                     x86_64                    2.0-0.52.20160912git.el8                                    baseos                        321 k
 openssl-devel                                 x86_64                    1:1.1.1k-9.el8_7                                            baseos                        2.3 M
 pkgconf-pkg-config                            x86_64                    1.4.2-1.el8                                                 baseos                         14 k
 python-rpm-macros                             noarch                    3-43.el8                                                    appstream                      15 k
 python36-devel                                x86_64                    3.6.8-38.module+el8.5.0+671+195e4563                        appstream                      15 k
 readline-devel                                x86_64                    7.0-10.el8                                                  baseos                        203 k
 redhat-rpm-config                             noarch                    130-1.el8                                                   appstream                      89 k
 sqlite-devel                                  x86_64                    3.26.0-17.el8_7                                             baseos                        164 k
 systemtap-sdt-devel                           x86_64                    4.7-1.el8                                                   appstream                      86 k
 tcl-devel                                     x86_64                    1:8.6.8-2.el8                                               baseos                        190 k
 tix-devel                                     x86_64                    1:8.4.3-23.el8                                              powertools                    144 k
 tk-devel                                      x86_64                    1:8.6.8-1.el8                                               appstream                     497 k
 valgrind-devel                                x86_64                    1:3.19.0-1.el8                                              appstream                      93 k
 xz-devel                                      x86_64                    5.2.4-4.el8_6                                               baseos                         61 k
 zlib-devel                                    x86_64                    1.2.11-21.el8_7                                             baseos                         57 k`

Should the Dockerfile include this pattern instead? There looks like there are other dependencies that may be missing as well.
