### ISSUE TITLE
  https://cdn.rstudio.com/python/ubuntu-2204/pkgs/python-3.10.11_1_amd64.deb unable to download through jfrog 

### ISSUE THREAD

**Issue by prasadareti143** [rstudio/python-builds#82]
Hi Team,

actually we are trying to  https://cdn.rstudio.com/python/ubuntu-2204/pkgs/python-3.10.11_1_amd64.deb

we created the remote repo in jfrog and trying to downloading the above versio of python when i trying to install;in its saying file got corrupted can any one suggest on this issue please

**Comment by edavidaja** [comment]
Hi! If this is still a problem for you, could you send an email to support@posit.co? Thanks!
